name: Automatic data transfer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # run daily at midnight

jobs:
  backup_copy_restore_and_log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        #trying to login to the production remote server 
      - name: ssh on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SOURCE_HOST }} #ip address of production
          username: ${{ secrets.SOURCE_USER }} #expertiza 
          key: ${{ secrets.SOURCE_KEY }} #private key
          script : |
            sudo mysqldump -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" ${{ secrets.SYNC_MYSQL_SOURCE_DB }} > production_db_dump.sql
            mkdir -p db_backups
            cp production_db_dump.sql db_backups/db_dump_production_$(date -d "today" +"%Y%m%d%H%M").sql
            echo "backup copied to db_backup">> log_file.txt
            scp production_db_dump.sql ${{ secrets.ACTOR }}@github.com:db/production_db_dump.sql
            
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: upload production_db_dump.sql file
          path: db/production_db_dump.sql
